name: Terraform Plan

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/myapp-terraform-role
          aws-region: ap-south-1


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0


      - name: Terraform Init
        run: terraform init


      - name: Terraform Format Check
        run: terraform fmt -check -recursive


      - name: Terraform Validate
        run: terraform validate


      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      #This step uses actions/github-script to call the GitHub API and post the plan output as a comment on the PR.    
      #steps.plan.outputs.stdout — reads the terminal output from the plan step using its id: plan.
      #steps.plan.outcome — reads whether it passed or failed.
      #context.issue.number — the PR number, automatically available.

      - name: Post plan as PR comment
        uses: actions/github-script@v7
        with:
          script: |
            const output = `### Terraform Plan
            \`\`\`
            ${{ steps.plan.outputs.stdout }}
            \`\`\`
            Status: ${{ steps.plan.outcome }}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      
      #continue-on-error: true That prevented it from stopping the workflow. 
      # Now we explicitly fail after posting the comment:
      - name: Fail if plan failed
        if: steps.plan.outcome == 'failure'
        run: exit 1
